language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t smk781/react-test -f ./client/Dockerfile.dev ./client/

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t smk781/multi-client ./client
  - docker build -t smk781/multi-server ./server
  - docker build -t smk781/multi-nginx ./nginx
  - docker build -t smk781/worker ./worker
  # Log in to the Docker CLI
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Take those images and push them to Docker Hub
  docker push smk781/multi-client
  docker push smk781/multi-server
  docker push smk781/multi-nginx
  docker push smk781/worker
  # Log out of the Docker CLI
  docker logout